{
 "title": "Nessie",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": { "query": "label_values(application)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(jvm_info_total{application=\"$application\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Tiered Version Store Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nessie Tiered-Version Cache Hits & Misses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "increase(nessie_versioned_tiered_cache_request_count[1m])",
     "legendFormat": "requests"
    },
    {
     "expr": "increase(nessie_versioned_tiered_cache_hit_count[1m])",
     "legendFormat": "hits"
    },
    {
     "expr": "increase(nessie_versioned_tiered_cache_miss_count[1m])",
     "legendFormat": "misses"
    },
    {
     "expr": "increase(nessie_versioned_tiered_cache_eviction_count[1m])",
     "legendFormat": "evictions"
    }
   ]
  },
  {
   "title": "Nessie Tiered-Version Cache Hit & Miss Ratios",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nessie_versioned_tiered_cache_hit_rate ",
     "legendFormat": "hit-rate"
    },
    {
     "expr": "nessie_versioned_tiered_cache_miss_rate ",
     "legendFormat": "miss-rate"
    }
   ]
  },
  { "title": "Version Store", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 } },
  {
   "title": "Nessie Commit",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 101 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.75, sum(rate(nessie_version_store_request_seconds_bucket{application=\"$application\", instance=\"$instance\", request=\"commit\"}[1m])) by (error, le))",
     "legendFormat": "p75 err={{error}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(nessie_version_store_request_seconds_bucket{application=\"$application\", instance=\"$instance\", request=\"commit\"}[1m])) by (error, le))",
     "legendFormat": "p95 err={{error}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(nessie_version_store_request_seconds_bucket{application=\"$application\", instance=\"$instance\", request=\"commit\"}[1m])) by (error, le))",
     "legendFormat": "p99 err={{error}}"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(nessie_version_store_request_seconds_bucket{application=\"$application\", instance=\"$instance\", request=\"commit\"}[1m])) by (error, le))",
     "legendFormat": "p999 err={{error}}"
    },
    {
     "expr": "max(nessie_version_store_request_seconds_max{application=\"$application\", instance=\"$instance\", request=\"commit\"}) by (error)",
     "legendFormat": "max err={{error}}"
    }
   ]
  },
  {
   "title": "Nessie Commit (rate)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 101 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nessie_version_store_request_seconds_count{application=\"$application\", instance=\"$instance\", request=\"commit\"}[1m])) by (error)",
     "legendFormat": "rate err={{error}}"
    },
    {
     "expr": "sum(rate(nessie_version_store_commit_retries{application=\"$application\", instance=\"$instance\"}[1m]))",
     "legendFormat": "retries"
    },
    {
     "expr": "sum(rate(nessie_version_store_commit_failures{application=\"$application\", instance=\"$instance\"}[1m]))",
     "legendFormat": "failures"
    }
   ]
  },
  {
   "title": "Nessie To-Ref",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.75, sum(rate(nessie_version_store_request_seconds_bucket{application=\"$application\", instance=\"$instance\", request=\"to-ref\"}[1m])) by (error, le))",
     "legendFormat": "p75 err={{error}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(nessie_version_store_request_seconds_bucket{application=\"$application\", instance=\"$instance\", request=\"to-ref\"}[1m])) by (error, le))",
     "legendFormat": "p95 err={{error}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(nessie_version_store_request_seconds_bucket{application=\"$application\", instance=\"$instance\", request=\"to-ref\"}[1m])) by (error, le))",
     "legendFormat": "p99 err={{error}}"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(nessie_version_store_request_seconds_bucket{application=\"$application\", instance=\"$instance\", request=\"to-ref\"}[1m])) by (error, le))",
     "legendFormat": "p999 err={{error}}"
    },
    {
     "expr": "max(nessie_version_store_request_seconds_max{application=\"$application\", instance=\"$instance\", request=\"to-ref\"}) by (error)",
     "legendFormat": "max err={{error}}"
    }
   ]
  },
  {
   "title": "Nessie To-Ref (rate)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 104 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nessie_version_store_request_seconds_count{application=\"$application\", instance=\"$instance\", request=\"to-ref\"}[1m])) by (error)",
     "legendFormat": "rate err={{error}}"
    }
   ]
  },
  {
   "title": "Nessie Get Named Refs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 112 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.75, sum(rate(nessie_version_store_request_seconds_bucket{application=\"$application\", instance=\"$instance\", request=\"get-named-refs\"}[1m])) by (error, le))",
     "legendFormat": "p75 err={{error}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(nessie_version_store_request_seconds_bucket{application=\"$application\", instance=\"$instance\", request=\"get-named-refs\"}[1m])) by (error, le))",
     "legendFormat": "p95 err={{error}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(nessie_version_store_request_seconds_bucket{application=\"$application\", instance=\"$instance\", request=\"get-named-refs\"}[1m])) by (error, le))",
     "legendFormat": "p99 err={{error}}"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(nessie_version_store_request_seconds_bucket{application=\"$application\", instance=\"$instance\", request=\"get-named-refs\"}[1m])) by (error, le))",
     "legendFormat": "p999 err={{error}}"
    },
    {
     "expr": "max(nessie_version_store_request_seconds_max{application=\"$application\", instance=\"$instance\", request=\"get-named-refs\"}) by (error)",
     "legendFormat": "max err={{error}}"
    }
   ]
  },
  {
   "title": "Nessie Get Named Refs (rate)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 112 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nessie_version_store_request_seconds_count{application=\"$application\", instance=\"$instance\", request=\"get-named-refs\"}[1m])) by (error)",
     "legendFormat": "rate err={{error}}"
    }
   ]
  },
  {
   "title": "Nessie Get Commits",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 113 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.75, sum(rate(nessie_version_store_request_seconds_bucket{application=\"$application\", instance=\"$instance\", request=\"get-commits\"}[1m])) by (error, le))",
     "legendFormat": "p75 err={{error}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(nessie_version_store_request_seconds_bucket{application=\"$application\", instance=\"$instance\", request=\"get-commits\"}[1m])) by (error, le))",
     "legendFormat": "p95 err={{error}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(nessie_version_store_request_seconds_bucket{application=\"$application\", instance=\"$instance\", request=\"get-commits\"}[1m])) by (error, le))",
     "legendFormat": "p99 err={{error}}"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(nessie_version_store_request_seconds_bucket{application=\"$application\", instance=\"$instance\", request=\"get-commits\"}[1m])) by (error, le))",
     "legendFormat": "p999 err={{error}}"
    },
    {
     "expr": "max(nessie_version_store_request_seconds_max{application=\"$application\", instance=\"$instance\", request=\"get-commits\"}) by (error)",
     "legendFormat": "max err={{error}}"
    }
   ]
  },
  {
   "title": "Nessie Get Commits (rate)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 113 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nessie_version_store_request_seconds_count{application=\"$application\", instance=\"$instance\", request=\"get-commits\"}[1m])) by (error)",
     "legendFormat": "rate err={{error}}"
    }
   ]
  },
  { "title": "Dynamo", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 200 } },
  {
   "title": "Dynamo API Call Successful",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 202 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation) (rate(DynamoDB_ApiCallSuccessful_summary_count{application=\"$application\", instance=\"$instance\"}[1m]))",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "sum(rate(DynamoDB_ApiCallSuccessful_summary_count{application=\"$application\", instance=\"$instance\"}[1m]))",
     "legendFormat": "Sum"
    }
   ]
  },
  {
   "title": "Dynamo API Call Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 202 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(DynamoDB_ApiCallDuration_seconds_bucket{application=\"$application\", instance=\"$instance\"}[1m])) by (operation, le))",
     "legendFormat": "p95 {{operation}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(DynamoDB_ApiCallDuration_seconds_bucket{application=\"$application\", instance=\"$instance\"}[1m])) by (operation, le))",
     "legendFormat": "p99 {{operation}}"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(DynamoDB_ApiCallDuration_seconds_bucket{application=\"$application\", instance=\"$instance\"}[1m])) by (operation, le))",
     "legendFormat": "p999 {{operation}}"
    },
    {
     "expr": "max(DynamoDB_ApiCallDuration_seconds_max{application=\"$application\", instance=\"$instance\"}) by (operation)",
     "legendFormat": "max {{operation}}"
    }
   ]
  },
  {
   "title": "Dynamo Received Record Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 203 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation) (rate(DynamoDB_ReceivedRecordCount_summary_count{application=\"$application\", instance=\"$instance\"}[1m]))",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "sum by (application, instance) (rate(DynamoDB_ReceivedRecordCount_summary_count{application=\"$application\", instance=\"$instance\"}[1m]))",
     "legendFormat": "Sum"
    }
   ]
  },
  {
   "title": "Dynamo Requested Record Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 203 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation) (rate(DynamoDB_RequestedRecordCount_summary_count{application=\"$application\", instance=\"$instance\"}[1m]))",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "sum by (application, instance) (rate(DynamoDB_RequestedRecordCount_summary_count{application=\"$application\", instance=\"$instance\"}[1m]))",
     "legendFormat": "Sum"
    }
   ]
  },
  {
   "title": "Dynamo Consumed Capacity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 210 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation) (rate(DynamoDB_ConsumedCapacity_summary_count{application=\"$application\", instance=\"$instance\"}[1m]))",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "sum by (application, instance) (rate(DynamoDB_ConsumedCapacity_summary_count{application=\"$application\", instance=\"$instance\"}[1m]))",
     "legendFormat": "Sum"
    }
   ]
  },
  { "title": "Threads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 300 } },
  {
   "title": "Nessie Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 301 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "executor_active_threads{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "Active Threads"
    },
    {
     "expr": "executor_pool_core_threads{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "Core Threads"
    },
    {
     "expr": "executor_queue_remaining_tasks{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "Remaining Tasks"
    }
   ]
  }
 ]
}