apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nessie.fullname" . }}
  labels:
    {{- include "nessie.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "nessie.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nessie.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "nessie.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.Version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if or (eq .Values.versionStoreType "ROCKSDB") (eq .Values.versionStoreType "ROCKS") }}
          volumeMounts:
            - name: rocks-storage
              mountPath: /rocks-nessie
          {{- end }}
          env:
            - name: NESSIE_VERSION_STORE_TYPE
              value: {{ .Values.versionStoreType }}

            {{- if .Values.logLevel }}
            - name: QUARKUS_LOG_LEVEL
              value: {{ .Values.logLevel }}
            - name: QUARKUS_LOG_CONSOLE_LEVEL
              value: {{ .Values.logLevel }}
            - name: QUARKUS_LOG_FILE_LEVEL
              value: {{ .Values.logLevel }}
            {{- if or (eq .Values.logLevel "DEBUG") (eq .Values.logLevel "TRACE") }}
            - name: QUARKUS_LOG_MIN_LEVEL
              value: {{ .Values.logLevel }}
            {{- end }}
            {{- end }}

            {{- if or (eq .Values.versionStoreType "DYNAMODB") (eq .Values.versionStoreType "DYNAMO") }}
            {{- if .Values.dynamodb.region }}
            - name: AWS_REGION
              value: {{ .Values.dynamodb.region }}
            {{- end }}
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.dynamodb.secret.name }}
                  key: {{ .Values.dynamodb.secret.awsAccessKeyId }}
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.dynamodb.secret.name }}
                  key: {{ .Values.dynamodb.secret.awsSecretAccessKey }}
            {{- end }}

            {{- if eq .Values.versionStoreType "CASSANDRA" }}
            - name: QUARKUS_CASSANDRA_KEYSPACE
              value: {{ .Values.cassandra.keyspace }}
            - name: QUARKUS_CASSANDRA_CONTACT_POINTS
              value: {{ .Values.cassandra.contactPoints }}
            {{- if .Values.cassandra.localDatacenter }}
            - name: QUARKUS_CASSANDRA_LOCAL_DATACENTER
              value: {{ .Values.cassandra.localDatacenter }}
            {{- end}}
            {{- if .Values.cassandra.auth.username }}
            - name: QUARKUS_CASSANDRA_AUTH_USERNAME
              value: {{ .Values.cassandra.auth.username }}
            - name: QUARKUS_CASSANDRA_AUTH_PASSWORD
              value: {{ .Values.cassandra.auth.password }}
            {{- end}}
            {{- end }}

            {{- if eq .Values.versionStoreType "ROCKSDB" }}
            - name: NESSIE_VERSION_STORE_PERSIST_ROCKS_DATABASE_PATH
              value: /rocks-nessie
            {{- end }}
            {{- if eq .Values.versionStoreType "ROCKS" }}
            - name: NESSIE_VERSION_STORE_ROCKS_DB_PATH
              value: /rocks-nessie
            {{- end }}

            {{- if or (eq .Values.versionStoreType "MONGODB") (eq .Values.versionStoreType "MONGO") }}
            {{- if .Values.mongodb.name }}
            - name: QUARKUS_MONGODB_DATABASE
              value: {{ .Values.mongodb.name }}
            {{- end }}
            {{- if .Values.mongodb.connectionString }}
            - name: QUARKUS_MONGODB_CONNECTION_STRING
              value: {{ .Values.mongodb.connectionString }}
            {{- end }}
            {{- if .Values.mongodb.secret.name }}
            - name: QUARKUS_MONGODB_CREDENTIALS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mongodb.secret.name }}
                  key: {{ .Values.mongodb.secret.username }}
            - name: QUARKUS_MONGODB_CREDENTIALS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mongodb.secret.name }}
                  key: {{ .Values.mongodb.secret.password }}
            {{- end }}
            {{- end }}

            {{- if or (eq .Values.versionStoreType "JDBC") (eq .Values.versionStoreType "TRANSACTIONAL") }}
            - name: QUARKUS_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.secret.name }}
                  key: {{ .Values.postgres.secret.username }}
            - name: QUARKUS_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.secret.name }}
                  key: {{ .Values.postgres.secret.password }}
            - name: QUARKUS_DATASOURCE_JDBC_URL
              value: {{ .Values.postgres.jdbcUrl }}
            {{- end }}

            {{- if .Values.authentication.enabled }}
            - name: NESSIE_SERVER_AUTHENTICATION_ENABLED
              value: {{ .Values.authentication.enabled | quote }}
            {{- if .Values.authentication.oidcAuthServerUrl }}
            - name: QUARKUS_OIDC_AUTH_SERVER_URL
              value: {{ .Values.authentication.oidcAuthServerUrl }}
            {{- end }}
            {{- if .Values.authentication.oidcClientId }}
            - name: QUARKUS_OIDC_CLIENT_ID
              value: {{ .Values.authentication.oidcClientId }}
            {{- end }}
            {{- end }}

            {{- if .Values.authorization.enabled }}
            - name: NESSIE_SERVER_AUTHORIZATION_ENABLED
              value: {{ .Values.authorization.enabled | quote }}
            {{- if .Values.authorization.rules }}
            {{- range $ruleId, $rule := .Values.authorization.rules }}
            - name: NESSIE_SERVER_AUTHORIZATION_RULES_{{ upper $ruleId }}
              value: {{ $rule }}
            {{- end }}
            {{- end }}
            {{- end }}

            {{- if .Values.tracing.enabled }}
            - name: QUARKUS_OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ .Values.tracing.endpoint | quote }}
            {{- if .Values.tracing.attributes }}
            - name: QUARKUS_OTEL_TRACER_RESOURCE_ATTRIBUTES
              value: "{{- include "nessie.dictToString" .Values.tracing.attributes }}"
            {{- end }}
            {{- if .Values.tracing.sample }}
            {{ if eq .Values.tracing.sample "all" }}
            - name: QUARKUS_OTEL_TRACER_SAMPLER
              value: "parentbased_always_on"
            {{- else if eq .Values.tracing.sample "none" }}
            - name: QUARKUS_OTEL_TRACER_SAMPLER
              value: "always_off"
            {{- else }}
            - name: QUARKUS_OTEL_TRACER_SAMPLER
              value: "parentbased_traceidratio"
            - name: QUARKUS_OTEL_TRACER_SAMPLER_ARG
              value: {{ .Values.tracing.sample | quote }}
            {{- end }}
            {{- end }}
            {{- end }}

            {{ list .Values.advancedConfig "" | include "nessie.propsToEnvVars" | nindent 12 }}

            {{- if .Values.extraEnv }}
            {{- toYaml .Values.extraEnv | nindent 12 }}
            {{- end }}
          ports:
            - name: nessie-server
              containerPort: 19120
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 19120
              scheme: HTTP
            initialDelaySeconds: 2
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 19120
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 45
            successThreshold: 1
            timeoutSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if eq .Values.versionStoreType "ROCKS" }}
      volumes:
        - name: rocks-storage
          persistentVolumeClaim:
            claimName: {{ include "nessie.fullname" . }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
