/*
 * Copyright (C) 2020 Dremio
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.projectnessie.versioned.util;

import java.time.Duration;
import java.util.concurrent.ThreadLocalRandom;
import java.util.function.Function;

import javax.annotation.Nonnull;

import com.google.common.annotations.VisibleForTesting;
import com.google.common.util.concurrent.Uninterruptibles;

public class BackoffState {
  private final BackoffConfig config;
  private final long startedNanos;
  private int retries;

  public BackoffState(@Nonnull BackoffConfig config) {
    this.config = config;
    this.startedNanos = currentTimeNanos();
  }

  @VisibleForTesting
  long currentTimeNanos() {
    return System.nanoTime();
  }

  @VisibleForTesting
  void sleep(Duration sleep) {
    Uninterruptibles.sleepUninterruptibly(sleep);
  }

  /**
   * Call before retrying the next attempt, will throw the exception generated by the
   * {@code failureSupplier} function, when no more retries are allowed.
   *
   * @param failureSupplier receives the failure reason, something like {@code "after 5 attempts"}
   *                        and returns the exception to throw.
   * @param <E> Exception type to throw
   * @throws E Exception returned by the {@code failureSupplier} function, when no more retries
   *     should be done.
   */
  public <E extends Exception> void retry(@Nonnull Function<String, E> failureSupplier) throws E {
    if (config.retries() == 0 && config.maxTime().isZero()) {
      throw failureSupplier.apply("immediately");
    }

    if (config.retries() > 0 && config.retries() <= retries) {
      throw failureSupplier.apply(String.format("after %d retries", retries));
    }

    if (!config.maxTime().isZero()) {
      Duration duration = Duration.ofNanos(currentTimeNanos() - startedNanos);
      if (config.maxTime().compareTo(duration) <= 0) {
        throw failureSupplier.apply(String.format("after %s", duration));
      }
    }

    retries++;

    if (!config.retrySleep().isZero()) {
      long baseNanos = config.retrySleep().toNanos();
      double multiplier = Math.max(1d, config.multiplier());
      long sleepNanos = (long) (baseNanos * Math.pow(multiplier, retries - 1));

      double jitter = config.jitter();
      if (jitter > 0d && jitter < 1d) {
        long jitterBound = (long) (sleepNanos * jitter);
        long jitterNanos = ThreadLocalRandom.current().nextLong(jitterBound);

        sleepNanos -= jitterNanos;
      }

      sleep(Duration.ofNanos(sleepNanos));
    }
  }

  /**
   * Number of current attempt.
   * @return Number of current attempt.
   */
  public int getTry() {
    return retries;
  }
}
