name: Main CI

on:
  push:
    branches:
      - main
      - release-*
    paths-ignore:
      - 'LICENSE'
      - 'NOTICE'
      - '**.md'
      - '!site/**'
      - '.github/renovate.json5'
      - '.github/workflows/release*.yml'
      - '.github/workflows/check*.yml'
      - '.idea/**'
      - '.editorconfig'

jobs:
  java:
    name: Java/Maven
    runs-on: ubuntu-20.04
    env:
      SPARK_LOCAL_IP: localhost
      MAVEN_USERNAME: ${{ secrets.OSSRH_ACCESS_ID }}

    steps:
    - uses: actions/checkout@v3
    - name: Setup runner
      uses: ./.github/actions/setup-runner
    - name: Setup Java, Gradle
      uses: ./.github/actions/dev-tool-java
      with:
        gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}

    - name: Gradle / spotless
      uses: gradle/gradle-build-action@v2
      with:
        # 'spotlessCheck' separate: workaround until https://github.com/diffplug/spotless/issues/1215 is fixed
        arguments: spotlessCheck

    - name: Gradle / compile
      uses: gradle/gradle-build-action@v2
      with:
        arguments: checkstyleMain checkstyleTest jar testClasses

    - name: Gradle / unit test
      uses: gradle/gradle-build-action@v2
      with:
        arguments: test

    - name: Gradle / check incl. integ-test
      uses: gradle/gradle-build-action@v2
      with:
        # '-x spotlessCheck': workaround until https://github.com/diffplug/spotless/issues/1215 is fixed
        arguments: check -x spotlessCheck

    - name: Gradle / Gatling simulations
      uses: gradle/gradle-build-action@v2
      with:
        arguments: gatlingRun

    - name: Gradle / assemble + publish local
      uses: gradle/gradle-build-action@v2
      with:
        arguments: |
          assemble
          codeCoverageReport -x test -x intTest
          publishToMavenLocal
          -Puber-jar

    - name: Gradle / build tools integration tests
      uses: gradle/gradle-build-action@v2
      with:
        arguments: buildToolsIntegrationTest

    - name: Capture Test Reports
      uses: actions/upload-artifact@v3
      if: ${{ failure() }}
      with:
        name: test-results
        path: |
          **/build/reports/*
          **/build/test-results/*

    - name: Capture Results
      uses: ./.github/actions/ci-results

  native:
    name: Java/Maven/Native
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - name: Setup runner
        uses: ./.github/actions/setup-runner
        with:
          more-memory: 'true'
      - name: Setup Java, Gradle
        uses: ./.github/actions/dev-tool-java

      - name: Gradle / integration test native
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: true
          arguments: |
            --no-daemon
            :nessie-quarkus:quarkusBuild
            :nessie-quarkus:intTest
            -Pnative
            -Pdocker

      - name: Capture Test Reports
        uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
          name: test-results-native
          path: |
            **/build/reports/*
            **/build/test-results/*

  jackson-tests:
    name: Jackson Integration Tests
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - name: Setup runner
        uses: ./.github/actions/setup-runner
      - name: Setup Java, Gradle
        uses: ./.github/actions/dev-tool-java

      # These steps are "too quick" to justify a matrix job
      - name: Jackson compatibility tests / 2.6.4 for Spark 2.4.4
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: true
          arguments: :nessie-client:test -Pjackson-tests=2.6.4
      - name: Jackson compatibility tests / 2.10.0 for Spark 3.0.1
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :nessie-client:test -Pjackson-tests=2.10.0
      - name: Jackson compatibility tests / 2.11.4 for Spark 3.0.1
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :nessie-client:test -Pjackson-tests=2.11.4
      - name: Jackson compatibility tests / 2.12.5 for Spark 3.0.1
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :nessie-client:test -Pjackson-tests=2.12.5

      - name: Capture Test Reports
        uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
          name: test-results-jackson
          path: |
            **/build/reports/*
            **/build/test-results/*

  python:
    name: Python
    runs-on: ubuntu-20.04
    env:
      working-directory: ./python
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']

    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: ./.github/actions/dev-tool-python
      with:
        python-version: ${{ matrix.python-version }}
    - name: Test with tox
      run: tox
      working-directory: ${{env.working-directory}}
    - uses: codecov/codecov-action@v3
      if: github.repository_owner == 'projectnessie'
      continue-on-error: true
      with:
        verbose: true
        fail_ci_if_error: true
        flags: python
