# Copyright (C) 2020 Dremio
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# Projectnessie GitHub Pull-Request / Native-image tests

name: PR Build Check Native

on:
  pull_request:
    types: [labeled, opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  java:
    name: Java/Gradle Native
    runs-on: ubuntu-20.04
    env:
      WF_EXEC: ${{ contains(github.event.pull_request.labels.*.name, 'pr-native') }}
    steps:
      - uses: actions/checkout@v3.3.0
        if: env.WF_EXEC == 'true'
      - name: Setup runner
        if: env.WF_EXEC == 'true'
        uses: ./.github/actions/setup-runner
        with:
          more-memory: 'true'
      - name: Setup Java, Gradle
        if: env.WF_EXEC == 'true'
        uses: ./.github/actions/dev-tool-java

      - name: Gradle / integration test native
        if: env.WF_EXEC == 'true'
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: true
          arguments: |
            --no-watch-fs
            :nessie-quarkus:quarkusBuild
            :nessie-quarkus:intTest
            -Pnative
            -Pdocker
            --scan

      - name: Capture Test Reports
        uses: actions/upload-artifact@v3
        if: env.WF_EXEC == 'true' && failure()
        with:
          name: test-results-native
          path: |
            **/build/reports/*
            **/build/test-results/*
          retention-days: 3
