# Copyright (C) 2020 Dremio
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


name: PR Integrations Tests

on:
  pull_request:
    types: [labeled, opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  java:
    name: Integrations Tests
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'pr-integrations')
    env:
      NESSIE_DIR: ${{ github.workspace }}
      ICEBERG_DIR: ${{ github.workspace }}/integ-test-suite/target/git/iceberg
      TRINO_DIR: ${{ github.workspace }}/integ-test-suite/target/git/trino

      # The following settings make up the whole setup:
      # - Git commit in Nessie source tree (via the GH checkout action)
      # - configuration name as used in integ-test-suite/config.in.sh
      #
      # See integ-test-suite/setup_for_config.sh for instructions how to provide a custom
      # configuration that is not in config.in.sh.
      config_name: HEAD

    steps:
    - uses: actions/checkout@v3
    - name: Setup runner
      uses: ./.github/actions/setup-runner
    - name: Setup Java, Maven
      uses: ./.github/actions/dev-tool-java

    - name: Initialize tools integration tests
      run: integ-test-suite/scripts/init.sh

    - name: Configure
      run: integ-test-suite/scripts/setup_for_config.sh

    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ hashFiles('**/*.gradle') }}-${{ hashFiles('**/versions.props') }}
        restore-keys: gradle-

    - name: Build Nessie w/o Clients
      run: integ-test-suite/scripts/build-nessie.sh

    - name: Build Iceberg
      run: integ-test-suite/scripts/build-iceberg.sh

    #- name: Build Trino
    #  run: integ-test-suite/scripts/build-trino.sh

    - name: Build Nessie Clients
      run: integ-test-suite/scripts/build-nessie-2.sh

    - name: Test Nessie
      run: integ-test-suite/scripts/test-nessie.sh

    - name: Test Iceberg
      run: integ-test-suite/scripts/test-iceberg.sh

    #- name: Test Trino
    #  run: integ-test-suite/scripts/test-trino.sh

    - name: Integration Tests
      run: integ-test-suite/scripts/test-integrations.sh
