# Copyright (C) 2020 Dremio
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# Projectnessie GitHub Pull-Request / Helm

name: PR Helm

on:
  pull_request:
    types: [labeled, opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  helm-testing:
    name: Lint & Test Helm chart
    runs-on: ubuntu-20.04
    env:
      WF_EXEC: ${{ contains(github.event.pull_request.labels.*.name, 'pr-helm') }}
    steps:
      - name: Checkout
        if: env.WF_EXEC == 'true'
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0
      - name: Set up Helm
        if: env.WF_EXEC == 'true'
        uses: azure/setup-helm@v3
        with:
          version: v3.8.1
      - uses: actions/setup-python@v4
        if: env.WF_EXEC == 'true'
        with:
          python-version: '3.8'
      - name: Set up chart-testing
        if: env.WF_EXEC == 'true'
        uses: helm/chart-testing-action@v2.3.1

      - name: Run chart-testing (list-changed)
        if: env.WF_EXEC == 'true'
        id: list-changed
        run: |
          ct list-changed --target-branch ${{ github.event.repository.default_branch }}

      - name: Run chart-testing (lint)
        if: env.WF_EXEC == 'true'
        run: ct lint --debug --charts ./helm/nessie

      - name: Set up & Start Minikube
        if: env.WF_EXEC == 'true'
        uses: medyagh/setup-minikube@v0.0.11
        with:
          cache: false

      - name: Show pods
        if: env.WF_EXEC == 'true'
        run: kubectl get pods -A

      - name: Run chart-testing (install)
        if: env.WF_EXEC == 'true'
        run: ct install --debug --charts ./helm/nessie
