name: Site

on:
  push:
    branches: [ main ]
    paths:
      - 'site/**'
jobs:

  site:
    name: Build & Deploy Website
    runs-on: ubuntu-20.04
    if: ${{ github.repository == 'projectnessie/nessie' }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'pip'
          cache-dependency-path: 'site/requirements.txt'
      - name: Upgrade pip
        run: |
          # install pip=>20.1 to use "pip cache dir"
          python3 -m pip install --upgrade pip
      - name: Install dependencies
        run: python3 -m pip install -r ./site/requirements.txt
      - name: Generate Static Site
        run: mkdocs build
        working-directory: ./site
      - name: Deploy Static Site to GitHub
        uses: peaceiris/actions-gh-pages@v3
        with:
          external_repository: projectnessie/projectnessie.github.io
          publish_branch: main
          deploy_key: ${{ secrets.NESSIE_SITE_DEPLOY_KEY }}
          publish_dir: ./site/site
          cname: projectnessie.org
