name: Publish in-development builds from main

on:
  schedule:
    # Run daily on week days
    - cron:  '0 11,23 * * 1-5'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  java:
    name: Publish from main
    runs-on: ubuntu-20.04
    env:
      SPARK_LOCAL_IP: localhost
    if: github.repository_owner == 'projectnessie'

    steps:
      - uses: actions/checkout@v3
      - name: Setup runner
        uses: ./.github/actions/setup-runner
      - name: Setup Java, Maven
        uses: ./.github/actions/dev-tool-java

      - name: Gradle / publish snapshot
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.OSSRH_ACCESS_ID }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.OSSRH_TOKEN }}
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            publishToSonatype closeAndReleaseSonatypeStagingRepository
            -Prelease -Puber-jar

      - name: Gradle / build Docker container
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            --no-daemon
            :nessie-quarkus:quarkusBuild
            -Pnative
            -Pdocker

      - name: Push Docker images
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: |
          echo '${{ secrets.DOCKER_TOKEN }}' | docker login -u '${{ secrets.DOCKER_USERNAME }}' --password-stdin
          docker images --filter 'reference=projectnessie/nessie' --format '{{.ID}}\t{{.Tag}}' |
          while read IMAGE_ID IMAGE_TAG; do
            docker tag "$IMAGE_ID" "projectnessie/nessie-unstable:${IMAGE_TAG%-snapshot}"
            docker push "projectnessie/nessie-unstable:${IMAGE_TAG%-snapshot}"
          done
